name: tech_talk_drift
description: Drift tech talk

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Drift
  drift: ^2.4.2
  path: ^1.8.2
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0

  # Riverpod
  hooks_riverpod: ^2.3.2

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true